"""
Django settings for django_ecommerce project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import dj_database_url
from decouple import config, Csv
from corsheaders.defaults import default_headers, default_methods

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost', cast=Csv())
# Optional extra CSRF origins (comma-separated) e.g. CSRF_EXTRA_ORIGINS=frontend.example.com,admin.example.com
CSRF_EXTRA_ORIGINS = config('CSRF_EXTRA_ORIGINS', default='', cast=Csv())

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django_filters',
    'corsheaders',
    'allauth',
    'allauth.account',
    'crispy_forms',  # For enhanced form rendering in admin
    'crispy_bootstrap5',  # For enhanced form rendering in admin
    'django_seed',  # For seeding database

    'django_select2',
    'django_tables2',
    'django_summernote',

    # My apps
    'apps.user',
    'apps.dashboard',
    'apps.master',
    'apps.ecom',
    'apps.inventory',
    'apps.order',
    'apps.cms'
]

ROOT_URLCONF = 'django_ecommerce.urls'

AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Moved up: should be before CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django_ecommerce.handle_preflight.HandlePreflightMiddleware',  # removed: let django-cors-headers handle preflight
]

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = False  # changed: do not combine with credentials
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3012",
    "http://127.0.0.1:8000",
    "https://ampedup-five.vercel.app",
    "http://dev.ampedup.fit",
    "https://dev.ampedup.fit",
    "https://ecom.shezan.me",  # added: API host must allow browser origin
]

# Fixed setting name (was CORS_ALLOWED_ORIGIN_REGEXES - wrong). Keep only if you need regex origins.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:3012$",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    "tenant",
    "x-csrftoken",
    "x-requested-with",
    "x-guest-token",  # added: custom header used in fetch
]

# Optional: expose custom headers to frontend JS if you need to read them in responses
CORS_EXPOSE_HEADERS = [
    "x-guest-token",
]

# Cannot "allow all" for CSRF; must enumerate with scheme. Build dynamically from hosts.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3012",
    "http://127.0.0.1:8000",
    "https://ampedup-five.vercel.app",
    "http://dev.ampedup.fit",
    "https://dev.ampedup.fit",
]
# Add https/http variants for non-local hosts
for host in [h for h in ALLOWED_HOSTS if h not in ("localhost", "127.0.0.1")]:
    if "://" not in host:  # ensure plain host names get schemes
        CSRF_TRUSTED_ORIGINS += [f"https://{host}", f"http://{host}"]
    else:
        CSRF_TRUSTED_ORIGINS.append(host)
# Add any extra explicitly supplied origins (add schemes if missing)
for extra in CSRF_EXTRA_ORIGINS:
    if "://" not in extra:
        CSRF_TRUSTED_ORIGINS += [f"https://{extra}", f"http://{extra}"]
    else:
        CSRF_TRUSTED_ORIGINS.append(extra)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_ecommerce.wsgi.application'

# Database
DATABASES = {
    'default': dj_database_url.parse(config('DATABASE_URL', default='sqlite:///db.sqlite3'))
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']  # For development

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # added: allow session/cookie auth across origins
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# -------------------------------------------------
# Cache configuration (Redis preferred, fallback LocMem)
# -------------------------------------------------
REDIS_URL = config('REDIS_URL', default='')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            },
            'KEY_PREFIX': config('CACHE_KEY_PREFIX', default='ecom_admin'),
        }
    }
else:
    # Development / fallback cache
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ecom-admin-locmem',
        }
    }

# Public API cache controls
PUBLIC_API_CACHE_ENABLED = config('PUBLIC_API_CACHE_ENABLED', default=True, cast=bool)
PUBLIC_API_CACHE_TIMEOUT = config('PUBLIC_API_CACHE_TIMEOUT', default=300, cast=int)  # seconds
# Optional: allow disabling caching per environment quickly

LOGIN_URL = 'staff_login'
LOGIN_REDIRECT_URL = 'dashboard:home'  # added
LOGOUT_REDIRECT_URL = 'staff_login'  # added

SUMMERNOTE_CONFIG = {
    'iframe': False,
    'attachment_absolute_uri': False,

    'summernote': {
        'attachment_absolute_uri': False,
        # As an example, using Summernote Air-mode
        'airMode': False,

        # Change editor size
        'width': '100%',
        'height': '350',  # Reduced height from 800 to 300

        # Use proper language setting automatically (default)
        'lang': None,

        # Toolbar customization
        # https://summernote.org/deep-dive/#custom-toolbar-popover
        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'underline', 'clear']],
            ['fontname', ['fontname']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video']],
            ['view', ['fullscreen', 'codeview', 'help']],
        ],

    },

}
